### ISSUE TITLE
configuration /root/augmented/config.ru not found

### ISSUE THREAD

**Issue by vmfunc** [dangeru/augmented#1]
I know this repo is extremely old, and idk if you'll reply, but I still try to start an issue ><
I installed everything and when I start the project, it says me that the config is not found. Where is it ? what should I do ?

**Comment by vmfunc** [comment]
My bad, 

Now I have
```
Traceback (most recent call last):
        21: from /usr/local/bin/rackup:23:in `<main>'
        20: from /usr/local/bin/rackup:23:in `load'
        19: from /var/lib/gems/2.5.0/gems/rack-2.2.3/bin/rackup:5:in `<top (required)>'
        18: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:168:in `start'
        17: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
        16: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
        15: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
        14: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
        13: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
        12: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        11: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
        10: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
         9: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
         8: from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
         7: from /root/augmented/src/config.ru:7:in `block in <main>'
         6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         4: from /root/augmented/src/app.rb:9:in `<top (required)>'
         3: from /root/augmented/src/app.rb:9:in `require_relative'
         2: from /root/augmented/src/routes/augmented.rb:9:in `<top (required)>'
         1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- sanitize (LoadError)
```

**Comment by purifetchi** [comment]
It looks like you haven't installed the sanitize gem.

czw., 17 cze 2021, 11:41 użytkownik Geshi ***@***.***>
napisał:

**Comment by vmfunc** [comment]
@naomiEve I'll try when I'll be back home, thank you so much for replying even if it was not updated for 2 years

**Comment by vmfunc** [comment]
Alright, it's working, thank you !

**Comment by purifetchi** [comment]
My pleasure, glad it works!

pt., 18 cze 2021, 07:39 użytkownik Geshi ***@***.***> napisał:
